# EXPLODINGFreedomMod 5.0 Configuration
# by Madgeek1450 and DarthSalamon.

# Generic server information
server:
  # You should change this to your server's name
  name: EXPLODINGFreedom

  # The address your server is located at
  address: 176.9.122.104:25594
  
  # Shown at the server list
  motd: EXPLODINGFreedom All-OP - Spigot Versions 1.7 & 1.8 Vist us online at http://explodingfreedom.boards.net

  # Every word in the MOTD will be a different color unless prefixed by a color code
  colorful_motd: true

  # All players who show up as owner
  owners:
    - EXPLODINGTNT001
    
  # URL players should appeal for bans at
  ban_url: http://explodingfreedom.boards.net

  # URL players should appeal for permanent bans at
  permban_url: http://explodingfreedom.boards.net

# Blocking certain events
allow:
  fire_place: false
  fire_spread: false
  fluid_spread: false
  lava_place: false
  lava_damage: false
  water_place: false
  tnt_minecarts: false
  explosions: false

explosive_radius: 4.0

# Blocked commands:
#
# How blocked commands work:
# All sections described below are delimited by colon characters.
# Make sure that you block a command by its main command name, not an alias
# -as all aliases are blocked by default. Commands are case-insensitive.
#
# * The first section is a letter which indicates which rank may use this command
#   Valid ranks:
#   n - Nobody (Completely disabled)
#   c - Senior Admins (Console)
#   t - Telnet Admins (Console)
#   s - Super Admins (Any in-game admin)
#   o - Ops (Non-Ops won't be able to use it)
#
# * The second section is a letter which indicates what to do when a player executes that command.
#   Valid actions:
#   b - Block the command
#   a - Block the command and auto-eject that player (for ops and below)
#   u - Block the command and Return an "Unknown command" message (Used to hide commands)
#
# * The third section is the command to be blocked, prefixed with a slash
#
# * The fourth section is the message to send to the player when executing that command.
#   This should be ommited if unwanted. ChatColors are supported with the &-key. By default
#   -the starting ChatColor is set to gray. You can use the default 'That command is blocked.' message
#   by using a single underscore.
#
# Examples:
#   - 'n:b:/mail sendall:&4You can't send mails to everyone!'
#   - 's:a:/stop'
#   - 'n:b:/ban:_'
#
blocked_commands:
  # Disabled commands
  - 'n:b:/jail:Nice try! How about /cage?'
  - 'n:b:/nuke_'
  - 'n:b:/time:Server-side time changing is disabled. Please use /ptime to set your own personal time.'
  - 'n:b:/gamemode:Use /creative and /survival to set your gamemode.'
  - 'n:b:/gamerule:_'
  - 'n:b:/ban:Nice try, how about /gtfo'
  - 'n:b:/mute:Stop using /mute BISH'
  - 'n:b:/pt:Powertools suck stop using them'
  - 'n:b:/powertool:Powertools suck stop using them'
  - 'n:b:/epowertool:Powertools suck stop using them'
  - 'n:b:/ept:Powertools suck stop using them'
  - 'n:b:/pardon:_'
  - 'n:b:/ban-ip:_'
  - 'n:b:/pardon-ip:Nice try, how about "/glist unban"'
  - 'n:b:/toggledownfall:_'
  - 'n:b:/effect:Please use /potion to set effects.'
  - 'n:b:/enderchest:_'
  - 'n:b:/bukkit:Plugin specific commands are disabled'
  - 'n:b:/banip:Nice try, how about "/glist ban"'
  - 'n:b:/fg:_'
  - 'n:b:/kickall:_'
  - 'n:b:/tpall:You cant tp everyone!'
  - 'n:b:/bcast:_'
  - 'n:b:/banlist:Did you mean "/tfbanlist"'
  - 'n:b:/ipbanlist:Did you mean "/tfipbanlist"'
  - 'n:u:/cb:_'
  - 'n:b:/co:_'
  - 'n:b:/fopm:_'
  - 'n:u:/sys:_'
  - 'n:b:/tpall:/tpall sucks! STOP USING IT!'
  - 'n:b:/mute:nice try! How about /stfu'
  - 'o:b//generate_'	
  - 'o:b//hcyl_'	 
  - 'o:b//cyl_'	 
  - 'o:b//sphere_'	 
  - 'o:b//hsphere_'	 
  - 'o:b//pyramid_' 
  - 'o:b//hpyramid_'	 
  - 'o:b/forestgen_'	 
  - 'o:b/pumpkins_'
  - 'o:b/toggleplace_'		
  - 'o:b//fill_'	 
  - 'o:b//fillr_'
  - 'o:b//drain_'
  - 'o:b/fixwater_'	 
  - 'o:b/fixlava_' 
  - 'o:b/removeabove_'	 
  - 'o:b/removebelow_'	 
  - 'o:b/replacenear_'	 
  - 'o:b/removenear	_' 
  - 'o:b/snow_'	
  - 'o:b/thaw_'	 
  - 'o:b//ex_'	 
  - 'o:b/butcher_'	
  - 'o:b/remove_'	 
  - 'o:b//green_'			 
  - 'o:b/chunkinfo_'		
  - 'o:b/listchunks_'		
  - 's:b/delchunks_'		
  - 'o:b//_'		
  - 'o:b/sp single_'		
  - 'o:b/sp area_'	 
  - 'o:b/sp recur_'	 
  - 'o:b/tool_'	 
  - 'o:b/none_'		
  - 'o:b/info_'		
  - 'o:b/tree_'	 
  - 'o:b//repl_'	 
  - 'o:b//cycler_'		
  - 'o:b//tool_' 	 
  - 'o:b/brush_' 
  - 'o:b/size_'	 
  - 'o:b//mat_'	 
  - 'o:b//mask_'		
  - 'o:b//mask_'	 
  - 'o:b//gmask_'	 
  - 'o:b//restore_'	 
  - 'o:b//snapshot_' 	 
  - 'o:b/cs_'	 
  - 'o:b/.s_'	 
  - 'o:b/<script>.js_'	 
  - 'o:b//fast_'			 
  - 'o:b/biome_'		
  - 'o:b/biomelist_'		
  - 'o:b//setbiome_''s:u:/v:_'
  - 'o:b:/give:Please use "/i" instead'
  - 'o:b:/socialspy:_'
  - 'o:b:/kill:_'
  - 'o:b://generate:_'
  - 'o:b://:_'
  - 'o:_'
  - 'o:b//deform_'			 
  - 'o:b//hollow_'			 
  - 'o:b//regen_'		
  - 'o:b//move_'	 
  - 'o:b//naturalize_'
  - 'o:b//chunk	_'	
  - 'o:b//expand_'	 
  - 'o:b//contract_'	 
  - 'o:b//outset_'	 
  - 'o:b//inset_'	 
  - 'o:b//shift_'	 
  - 'o:b//size_'		
  - 'o:b//count_'	 
  - 'o:b//distr_'
  - 'o:b//pos1_'
  - 'o:b//pos2_'
  - 'o:b//set_'
  - 'o:b//replace_'
  - 'o:b//copy_'
  - 'o:b//schem_'
  - 'o:b//paste_'
  - 'o:b://wand:That command is blocked and is not allowed.'
  - 's:b//generate_'	
  - 's:b//hcyl_'	 
  - 's:b//cyl_'	 
  - 's:b//sphere_'	 
  - 's:b//hsphere_'	 
  - 's:b//pyramid_' 
  - 's:b//hpyramid_'	 
  - 's:b/forestgen_'	 
  - 's:b/pumpkins_'
  - 's:b/toggleplace_'		
  - 's:b//fill_'	 
  - 's:b//fillr_'
  - 's:b//drain_'
  - 's:b/fixwater_'	 
  - 's:b/fixlava_' 
  - 's:b/removeabove_'	 
  - 's:b/removebelow_'	 
  - 's:b/replacenear_'	 
  - 's:b/removenear	_' 
  - 's:b/snow_'	
  - 's:b/thaw_'	 
  - 's:b//ex_'	 
  - 's:b/butcher_'	
  - 's:b/remove_'	 
  - 's:b//green_'			 
  - 's:b/chunkinfo_'		
  - 's:b/listchunks_'		
  - 's:b/delchunks_'		
  - 's:b//_'		
  - 's:b/sp single_'		
  - 's:b/sp area_'	 
  - 's:b/sp recur_'	 
  - 's:b/tool_'	 
  - 's:b/none_'		
  - 's:b/info_'		
  - 's:b/tree_'	 
  - 's:b//repl_'	 
  - 's:b//cycler_'		
  - 's:b//tool_' 	 
  - 's:b/brush_' 
  - 's:b/size_'	 
  - 's:b//mat_'	 
  - 's:b//mask_'		
  - 's:b//mask_'	 
  - 's:b//gmask_'	 
  - 's:b//restore_'	 
  - 's:b//snapshot_' 	 
  - 's:b/cs_'	 
  - 's:b/.s_'	 
  - 's:b/<script>.js_'	 
  - 's:b//fast_'			 
  - 's:b/biome_'		
  - 's:b/biomelist_'		
  - 's:b//setbiome_''s:u:/v:_'
  - 's:b:/give:Please use "/i" instead'
  - 's:b:/socialspy:_'
  - 's:b:/kill:_'
  - 's:b://generate:_'
  - 's:b://:_'
  - 's:_'
  - 's:b//deform_'			 
  - 's:b//hollow_'			 
  - 's:b//regen_'		
  - 's:b//move_'	 
  - 's:b//naturalize_'
  - 's:b//chunk	_'	
  - 's:b//expand_'	 
  - 's:b//contract_'	 
  - 's:b//outset_'	 
  - 's:b//inset_'	 
  - 's:b//shift_'	 
  - 's:b//size_'		
  - 's:b//count_'	 
  - 's:b//distr_'
  - 's:b//pos1_'
  - 's:b//pos2_'
  - 's:b//set_'
  - 's:b//replace_'
  - 's:b//copy_'
  - 's:b//schem_'
  - 's:b//paste_'  
 
  
  

  # Superadmin commands
  - 's:b:/deopall:_'
  - 's:b:/kick:_'
  - 's:b:/mute:_'
  - 's:b:/superpickaxe:_'
  - 's:b:/brush:_'
  - 's:b:/mat:_'
  - 's:b:/tool:_'
  - 's:b://butcher:_'
  - 's:b:/scoreboard:Sorry, this command for for Super Administrators and above.'
  - 's:b:/setspawn:You are able to perform "/sethome" instead.'
  - 's:b:/co:You may report grief to any online administrator, just scream it...'
  - 's:b:/tpohere:Please use "/tpahere" instead of "/tpohere"'
  - 's:b:/tphere:Please use "/tpahere" instead of "/tphere"'
  - 'n:b:/cbtool:That will result in a Permban, k?'
  - 'n:u:/cb:_'
  - 'n:b:/co:_'
  - 'n:b:/fopm:_'
  - 'n:u:/sys:_'
  - 'n:b:/tpall:/tpall sucks! STOP USING IT!'
  - 'n:b:/mute:nice try! How about /stfu'
  - 's:b:/npc_'
  - 's:b:/citizens_'
  - 's:b//generate_'	
  - 's:b//hcyl_'	 
  - 's:b//cyl_'	 
  - 's:b//sphere_'	 
  - 's:b//hsphere_'	 
  - 's:b//pyramid_' 
  - 's:b//hpyramid_'	 
  - 's:b/forestgen_'	 
  - 's:b/pumpkins_'
  - 's:b/toggleplace_'		
  - 's:b//fill_'	 
  - 's:b//fillr_'
  - 's:b//drain_'
  - 's:b/fixwater_'	 
  - 's:b/fixlava_' 
  - 's:b/removeabove_'	 
  - 's:b/removebelow_'	 
  - 's:b/replacenear_'	 
  - 's:b/removenear	_' 
  - 's:b/snow_'	
  - 's:b/thaw_'	 
  - 's:b//ex_'	 
  - 's:b/butcher_'	
  - 's:b/remove_'	 
  - 's:b//green_'			 
  - 's:b/chunkinfo_'		
  - 's:b/listchunks_'		
  - 's:b/delchunks_'		
  - 's:b//_'		
  - 's:b/sp single_'		
  - 's:b/sp area_'	 
  - 's:b/sp recur_'	 
  - 's:b/tool_'	 
  - 's:b/none_'		
  - 's:b/info_'		
  - 's:b/tree_'	 
  - 's:b//repl_'	 
  - 's:b//cycler_'		
  - 's:b//tool_' 	 
  - 's:b/brush_' 
  - 's:b/size_'	 
  - 's:b//mat_'	 
  - 's:b//mask_'		
  - 's:b//mask_'	 
  - 's:b//gmask_'	 
  - 's:b//restore_'	 
  - 's:b//snapshot_' 	 
  - 's:b/cs_'	 
  - 's:b/.s_'	 
  - 's:b/<script>.js_'	 
  - 's:b//fast_'			 
  - 's:b/biome_'		
  - 's:b/biomelist_'		
  - 's:b//setbiome_''s:u:/v:_'
  - 's:b:/give:Please use "/i" instead'
  - 's:b:/socialspy:_'
  - 's:b:/kill:_'
  - 's:b://generate:_'
  - 's:b://:_'
  - 's:_'
  - 's:b//deform_'			 
  - 's:b//hollow_'			 
  - 's:b//regen_'		
  - 's:b//move_'	 
  - 's:b//naturalize_'
  - 's:b//chunk	_'	
  - 's:b//expand_'	 
  - 's:b//contract_'	 
  - 's:b//outset_'	 
  - 's:b//inset_'	 
  - 's:b//shift_'	 
  - 's:b//size_'		
  - 's:b//count_'	 
  - 's:b//distr_'
  - 's:b//pos1_'
  - 's:b//pos2_'
  - 's:b//set_'
  - 's:b//replace_'
  - 's:b//copy_'
  - 's:b//schem_'
  - 's:b//paste_'
    

  # Superadmin commands - Auto-eject
  - 's:a:/stop'
  - 's:a:/reload'
  - 's:a:/save-all'
  - 's:a:/save-on'
  - 's:a:/save-off'
  - 's:a:/clearhistory'
  - 's:a:/nuke'
  - 's:a:/mat'
  - 's:a://snow'
  - 's:a//pos1_'
  - 's:a//pos2_'
  - 's:a//set_'
  - 's:a//replace_'
  - 's:a//copy_'
  - 's:a//schem_'
  - 's:a//paste_'

    # Spigot commands
  - 's:a:/restart'
  - 's:b:/setblock'

# Automatically wipe dropped objects:
auto_wipe: true

# Nuking prevention
nukemonitor:
  enabled: true
  count_break: 40
  count_place: 40
  range: 10.0

freecam_trigger_count: 10

# Show all attempted commands in the log, will result in duplicate log messages:
preprocess_log: true

# Disable certain events
disable:
  night: true
  weather: true


# Enable misc. features:
landmines_enabled: false
mp44_enabled: true
tossmob_enabled: false
adminworld_enabled: true

# Moblimiter:

moblimiter:
  enabled: true
  max: 50
  disable:
    dragon: true
    ghast: true
    slime: true
    giant: true
    wither: true

# Flatlands
flatlands:
  generate: true
  # Flatlands generation parameters, uses CleanroomGenerator syntax - http://dev.bukkit.org/server-mods/cleanroomgenerator/
  generate_params: 16,stone,32,dirt,1,grass

# Admin-Only Mode
admin_only_mode: false

# Protected Areas - Protect areas so that only superadmins can directly modify blocks in those areas. WorldEdit and other such plugins might bypass this.
protectarea:
  enabled: true
  auto_protect_spawnpoints: true
  auto_protect_radius: 25.0

# Give the default CONSOLE senior admin privileges.
# Handy in development environments.
console_is_senior: true

# Host Sender Names - Names that indicate automated services or host-based consoles you want to block from using some commands.
# Make sure these are all lower-case.
host_sender_names:
  - remotebukkit

# Announcer
announcer:
  enabled: true

  # Interval between announcements, in seconds.
  interval: 30

  # Prefix for all announcements
  prefix: '&8[&4EXPLODINGFreedom&8] &b'

  announcements:
    - 'Be sure to visit our forums at &6http://explodingfreedom.boards.net/'
    - 'You can always review the server rules here: &6http://http://explodingfreedom.yolasite.com/'
    - 'If you aren''t OP, be sure to ask our friendly staff!'
    - 'Remember to &4&lNOT GRIEF!!!!&b or you get punished!'
    - 'Always respect staff and dont disrespect them!'
    - 'The &4Owner &bis &1&lEXPLODINGTNT001, The Co Owners are &6&lzthehorsekid &band &e&lXxNicozillaxX!'
    - 'If you wish to apply do /ai, /apply or /admininfo and follow the instructions!'
    - 'Having Fun? Go tell your Friends!'
    - 'Remember to remember the rules and help out!'
    - 'Hacking and &eDDoS/DOX/DoS&b threats are &4not&b allowed'
    - '&3Invisibility Potions&b are for &4EF Staff&b only and if a &cOP&b is caught with it they will be punished!'
    - 'Our &cChief Of Security&b is &c&lrobgreenwood&b!'
    - 'Remember to use &e/report <playrname> <reason> &bon abusive staff and other players and the staff will deal with them!'
    - 'For advertising, use &2THIS&b IP to tell others to join: &e176.9.122.104:25570&b'

# Players who cannot be banned by username
unbannable_usernames:
  - EXPLODINGTNT001
  - zthehorsekid
  - XxNicozillaxX
  - honeydew
  - xephos
  - captainsparklez
  - truemu
  - kiershar
  - fvdisco
  - sethbling
  - notch
  - jeb_
  - gamechap
  - bertiechap
  - vechs
  - antvenom
  - chimneyswift
  - deadmau5
  - etho
  - ethoslab
  - skydoesminecraft
  - skythekidrs
  - tobyturner
  - xxslyfoxhoundxx
  - paulsoaresjr
  - sips_
  - deadlox
  - xxslyxx
  - jeromeasf
  - dinnerbone
  - grumm
  - grum
  - evilseph
  - cavemanfilms
  - herobrine
  - whiteboy7thst
  - stampylonghead
  - stampylongnose
  - dantdm
  - gizzy14gazza

# TwitterBot - Used to allow superadmins to verify themselves using twitter
twitterbot:
  enabled: false
  url: ''
  secret: ''

# Pet Protect - Prevent tamed pets from being killed.
petprotect:
  enabled: false

# Logs Registration
logs:
  url: ''
  secret: ''

# Mojang service checker
service_checker_url: http://status.mojang.com/check

# HTTPD
httpd:
  enabled: true
  port: 28966
  public_folder: ./public_html

# Inactivity Auto-Kick (Requires Essentials)
autokick:
  enabled: true
  # autokick_threshold - Percentage of server player capacity used at which players will be automatically kicked for being inactive. Range: 0.0 - 1.0
  threshold: 0.9
  # autokick_time - Time, in seconds, after which a player should be kicked when inactive
  time: 120